### ISSUE TITLE
ringbuffer size should probaply be templated 

### ISSUE THREAD

**Issue by PatrickDekker98** [R2D2-2019/USART_library#38]
https://github.com/R2D2-2019/USART_library/blob/0e721f867893cb05040b74deb875294f8cca9fdb/code/headers/hardware_usart.hpp#L157

This sets the ring buffer to a set size that should be variable through a template variable.

**Comment by itzandroidtab** [comment]
Unfortunately the way it is currently implemented there is no way to add an extra template to the class. As then the handlers need to have the exact same parameters. So this won't be implemented, otherwise the user then needs to change template parameters in the hardware_usart.hpp usart_handler
